{% set name = "ndg-httpsclient" %}
{% set pypi_name = "ndg_httpsclient" %}
{% set version = "0.4.4" %}
{% set hash_type = "sha256" %}
{% set hash = "fba4d4798dcac2965874f24afb6631b4326baa4bd02505744d34f690c354856a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ pypi_name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - ndg_httpclient = ndg.httpsclient.utils:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - pyasn1
    - pyopenssl

test:
  imports:
    - ndg
    - ndg.httpsclient
    - ndg.httpsclient.test

about:
  home: https://github.com/cedadev/ndg_httpsclient
  license: BSD 3-Clause
  license_file: ndg/httpsclient/LICENSE
  summary: Provides enhanced HTTPS support for httplib and urllib2 using PyOpenSSL.
  doc_url: http://pythonhosted.org/ndg-httpsclient
  dev_url: https://github.com/cedadev/ndg_httpsclient

extra:
  recipe-maintainers:
    - goanpeca
