{% set name = "ndg_httpsclient" %}
{% set version = "0.4.3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "7bfd8c5cfcbc241a93ca6a4e45f952650f5c7ecf7c49b1dbcf5f4d390240be0b" %}

package:
  name: {{ name|lower| replace('_', '-') }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ file_ext }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  {{ hash_type }}: {{ hash_value }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - ndg_httpclient = ndg.httpsclient.utils:main

requirements:
  host:
    - python
    - setuptools
  run:
    - python
    - pyasn1 >=0.1.1
    - pyopenssl

test:
  imports:
    - ndg
    - ndg.httpsclient
    - ndg.httpsclient.test
  commands:
    - ndg_httpclient --help

about:
  home: https://github.com/cedadev/ndg_httpsclient
  license: BSD 3-Clause
  license_file: ndg/httpsclient/LICENSE
  summary: Provides enhanced HTTPS support for httplib and urllib2 using PyOpenSSL.
  description: |
    A HTTPS client implementation for httplib, http.client and urllib2 based on PyOpenSSL.
    PyOpenSSL provides a more fully featured SSL implementation over the default provided
    with Python and importantly enables full verification of the SSL peer.
  doc_url: http://pythonhosted.org/ndg-httpsclient
  dev_url: https://github.com/cedadev/ndg_httpsclient

extra:
  recipe-maintainers:
    - goanpeca
    - nehaljwani
