travis:
  secure:
    BINSTAR_TOKEN: QBglTLGMSl1LT3cPxGWzt5rrb1V/m84tu1KDAcehSoaLU7we2tNPDBcbY3YfegcbtkikX9klwbZXF6/nKdR0ekMi0pdwYKWN3RNTLsKhvOh8y65mW8jTREqYkia40Xl2i5W0KHm0chtg9wvnAlIdH0pXrZJvndmQtKG2cIaN7CHH3j+/MbmLxVC/U9keij0nwNvZ4g+IdBEqKDQvaQ0RsqoiJNFpMM+cHF3rZevfBTKS0tC2/03MoSz+nCAh6WFWGlZZ5JZaOZxtDzI2VselJ4ylb6ce+C2zA3LaJOBbOm/MORscqUZl63EvQEQLGm4gRJDKoisZ8RNCzP2Lt+zPrsUt724PjIIBKZalo1ZQwI+5tyNqSLZWxIfP8aknSVU+Z5bzDPYKwU38anh3yWrYFCOem2kSwARvs+xsmKLNtp9mWyTwzzT6jfIWffu0HLJG5qYZfarmqwwXpgxEWkwoMamtco1qubUeYUX20QN0zJTW9/nbedZxluecp2ryST8U3WV1bDrsPc5zx8OZc0bKrvaTb0Cpm11JWR+LVtidHHUThIdkPtVfRQ4E/Oag/IK+TiPV4oH1+jYJmcns8Z3BoTZlTyZTjMpHgTWa3ONR9UOOrP1ZpGc1TamDarVa2HxzCwu+vEIIlrVZVkiJce97MMF9hQXh2WNGNnsz3RayHrc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
