travis:
  secure:
    BINSTAR_TOKEN: OVQahLGUhH45+lIEBBCsjVOhGNs1b2t3UT3HZZiaasL8Lfkl+KnNTWVrk+71zQeTH0Fe9dnYCsMrWLwpeQ1R41KOZ5EKP07bIj8XZhBIrAnqJeUlUMeX7JZCWP329hPOSR0GBdEiI0hBej+pDmvDmZIYmMzSsUgCsuY9MoKR9TWq1Ee1YLvUtn9KxNxeVlye48TrlKQqem96ZSwi1/LH8v+8cXDg8PK491XPYq0R4WpJHAQ15CMqTbDMFoOR5QxJCD+0SIF3zUWLSg7Kxo+zQcxKq1HChdpd74xlNV5s3EgxCooOvBclmuEGKVdV7uuGt+1sIb6JvEs0nUPEIDKZHbmR1kAY3LrEi2XjCKD6bfUwzr/XPzuu58DQsHciMjJkOn1B/NSaJLgouWhlEGU0eivJO6QaOvhWa3bHufni7PJOcdYOzuI75SdfXIDi9o5O1Dp2PyXLP7qutLPGyDNPdnx52nzI1FoDe71YFgskvl0/QjOaaJ7fB+IlMy5u5MoQjZBJV7uMtAivJKtJZmxv0YwWPrBSvyM3DrDHdGjeHT8DlGy2daIvF+K4/kWekXg/EKQp22YrfJzHXrvU6bqXezdUIA1ZBPAwgLPZq55Hsrd76yVQhzj6k2AVI/4pkoAeLlbRQ4lh4FOPGtHBGTrBN0wCVZGsc4E3JCruQxulfHE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
