travis:
  secure:
    BINSTAR_TOKEN: Au3wU4tQlkXzzumHZLre0VRSr3eedRlOh1CL+B1wDnquucGeqABp/HQHprnjos76EXboA8ApqskEbM9tuefX1y7xAd/C0k+tVLAGmsxM0WJ1ym/01SGbvXVjdfx4gnMB/Sy2ALNp0WsEPIRV6tedx/y4NI1xSeGvaQ/KPiYdCfNXhb+KqatOTIJtCJvigiHzqP0hmQdsDii35H0I8kFflgFg92Mcu87FWhby1F/VRAxm2G/YYkrj6lvVWtZP0zRaA407yTbvneR0ccV9I/gWEnrd25RoJbFgt8odNd38dyVUIl7vR4qeNkYyJKbVgN3dZ1dulcWZMG0fT/vLntsTvbWmMUFssUyPZEH5sJn60uB3IqtO5ZPRlTY6RmtdCPAMWQOghizr752z15fUPLTpW0IoLXBkr/6xjZZ/fI6SOKNZhwLFCrYMBikKXfT1PKyQhax2XFQMeZ1NJvJowi4NbOS4C6II2UocEXhc4zlxS0Tl4WE8AdzX+qxPKU0eI5J/4ZQ8Q3SdzPpnNX5nZXTYfT3WpNPvA0Lw+dx6KR5ZVfZsgUCONW/LMMZDGHWM5krSSq+U63AVsueWRA1A1po9hhVBdbyvftMMTcZOXLZaqlU5eRtEuMKdXI6xcGp5Bs5rdp1zpXzAzqu8fuA9IeVTpQryAOavGdo4OuS4RCTS140=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
